//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EW.Unisystems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public Career()
        {
            this.Resource = new HashSet<Resource>();
        }
    
        public int IdCareer { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Resource> Resource { get; set; }
    }
}
