//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EW.Unisystems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeResource
    {
        public TypeResource()
        {
            this.Resources = new HashSet<Resource>();
        }
    
        public int IdResource { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Resource> Resources { get; set; }
    }
}
